UPDATE `client_citations`
SET `status` = CASE `status`
  WHEN 'LIVE_CITATION' THEN 'COMPLETE'
  WHEN 'REJECTED' THEN 'INCOMPLETE'
  WHEN 'IN_REVIEW' THEN 'PENDING'
  WHEN 'NOT_SYNCED' THEN 'PENDING'
  ELSE `status`
END
WHERE `status` IN ('LIVE_CITATION', 'REJECTED', 'IN_REVIEW', 'NOT_SYNCED');
