CREATE TABLE `scans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT UNSIGNED NOT NULL,
  `gbp_profile_id` BIGINT UNSIGNED NOT NULL,
  `keywords` JSON NOT NULL,
  `coverage_unit` VARCHAR(32) NOT NULL,
  `coverage_points` JSON NOT NULL,
  `labels` JSON NULL,
  `frequency` VARCHAR(32) NOT NULL,
  `repeat_time` VARCHAR(16) NOT NULL,
  `start_at` DATETIME(3) NOT NULL,
  `next_run_at` DATETIME(3) NOT NULL,
  `estimated_requests` INT UNSIGNED NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_scans_client_id`(`client_id`),
  INDEX `idx_scans_gbp_profile_id`(`gbp_profile_id`),
  INDEX `idx_scans_status`(`status`),
  INDEX `idx_scans_next_run_at`(`next_run_at`),
  INDEX `idx_scans_created_by`(`created_by`),
  CONSTRAINT `fk_scans_client` FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scans_gbp_profile` FOREIGN KEY (`gbp_profile_id`) REFERENCES `client_gbp_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scans_created_by` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `scan_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `total_requests` INT UNSIGNED NOT NULL,
  `completed_requests` INT UNSIGNED NOT NULL DEFAULT 0,
  `failed_requests` INT UNSIGNED NOT NULL DEFAULT 0,
  `triggered_by` BIGINT UNSIGNED NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finished_at` DATETIME(3) NULL,
  `summary` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_scan_runs_scan_id`(`scan_id`),
  INDEX `idx_scan_runs_status`(`status`),
  INDEX `idx_scan_runs_triggered_by`(`triggered_by`),
  INDEX `idx_scan_runs_started_at`(`started_at`),
  CONSTRAINT `fk_scan_runs_scan` FOREIGN KEY (`scan_id`) REFERENCES `scans`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scan_runs_triggered_by` FOREIGN KEY (`triggered_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `scan_results` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_run_id` BIGINT UNSIGNED NOT NULL,
  `keyword` VARCHAR(255) NOT NULL,
  `coordinate_label` VARCHAR(180) NULL,
  `latitude` DECIMAL(10,7) NOT NULL,
  `longitude` DECIMAL(10,7) NOT NULL,
  `rank_absolute` INT NULL,
  `rank_group` INT NULL,
  `matched_title` VARCHAR(255) NULL,
  `matched_domain` VARCHAR(255) NULL,
  `matched_place_id` VARCHAR(255) NULL,
  `matched_address` VARCHAR(255) NULL,
  `matched_phone` VARCHAR(64) NULL,
  `matched_rating` DECIMAL(3,2) NULL,
  `matched_item` JSON NULL,
  `api_log_id` BIGINT UNSIGNED NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_scan_results_scan_run_id`(`scan_run_id`),
  INDEX `idx_scan_results_keyword`(`keyword`),
  INDEX `idx_scan_results_matched_place_id`(`matched_place_id`),
  INDEX `idx_scan_results_api_log_id`(`api_log_id`),
  CONSTRAINT `fk_scan_results_scan_run` FOREIGN KEY (`scan_run_id`) REFERENCES `scan_runs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
